#!/bin/zsh

# If your connection is true, return your global and local IP, and copy local IP.

global=$(curl -s inet-ip.info)
local=$(ifconfig en0|grep inet|awk '{print $2}'|sed 1d)

if [ -z "$global" ]; then
  echo "\033[31mERROR: No connection\033[m"
  exit 1
fi

echo "\033[34mGlobal IP\033[m: $global"
echo "\033[35mLocal IP\033[m: $local"
echo $local | pbcopy

exit 0
